### PR TITLE
Update ProductRestAPIController_Test

### PR DESCRIPTION
**Pull request by Rajasundhar-95**
Changes has been done. Please review it and update

### CODE REVIEW

**Comment by Rajasundhar-95** [comment]
Gothrough the codes

**Review by AakarshanS09 — CHANGES_REQUESTED** [review]
I have through codes it looks good but could please go through codes once again

**Comment by Rajasundhar-95** [comment]
Yeah I have review it another time. It looks good.

**Review by AakarshanS09 — APPROVED** [review]
The changes has been accepted

**Pull request merged**
